
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 16 21:11:20 CST 2013
//----------------------------------------------------

package compiladores;

import java_cup.runtime.*;
import AST.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Apr 16 21:11:20 CST 2013
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\127\000\002\002\004\000\002\002\005\000\002\003" +
    "\002\000\002\003\004\000\002\004\002\000\002\004\004" +
    "\000\002\005\006\000\002\006\004\000\002\006\002\000" +
    "\002\007\003\000\002\007\005\000\002\010\023\000\002" +
    "\011\010\000\002\012\004\000\002\012\004\000\002\012" +
    "\002\000\002\013\002\000\002\013\004\000\002\013\004" +
    "\000\002\013\004\000\002\014\005\000\002\017\011\000" +
    "\002\037\004\000\002\037\005\000\002\015\002\000\002" +
    "\015\004\000\002\016\003\000\002\016\004\000\002\020" +
    "\003\000\002\020\003\000\002\021\005\000\002\022\005" +
    "\000\002\022\002\000\002\023\003\000\002\023\002\000" +
    "\002\024\004\000\002\024\006\000\002\025\005\000\002" +
    "\025\003\000\002\025\003\000\002\025\003\000\002\025" +
    "\003\000\002\026\005\000\002\026\010\000\002\026\007" +
    "\000\002\026\013\000\002\026\011\000\002\026\007\000" +
    "\002\026\011\000\002\027\004\000\002\027\002\000\002" +
    "\036\005\000\002\036\002\000\002\030\003\000\002\030" +
    "\014\000\002\031\003\000\002\031\003\000\002\032\003" +
    "\000\002\032\005\000\002\032\006\000\002\032\005\000" +
    "\002\032\010\000\002\033\003\000\002\033\003\000\002" +
    "\033\003\000\002\033\003\000\002\033\003\000\002\033" +
    "\007\000\002\033\007\000\002\033\004\000\002\033\005" +
    "\000\002\033\003\000\002\034\003\000\002\034\005\000" +
    "\002\034\002\000\002\035\003\000\002\035\003\000\002" +
    "\035\003\000\002\035\003\000\002\035\003\000\002\035" +
    "\003\000\002\035\003\000\002\035\003\000\002\035\003" +
    "\000\002\035\003\000\002\035\003\000\002\035\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\274\000\006\032\uffff\033\uffff\001\002\000\004\002" +
    "\276\001\002\000\006\032\006\033\ufffd\001\002\000\004" +
    "\064\267\001\002\000\006\032\ufffe\033\ufffe\001\002\000" +
    "\004\033\012\001\002\000\004\033\ufffc\001\002\000\004" +
    "\064\014\001\002\000\004\002\000\001\002\000\010\023" +
    "\020\062\016\063\017\001\002\000\004\023\221\001\002" +
    "\000\004\064\220\001\002\000\004\064\217\001\002\000" +
    "\004\034\021\001\002\000\004\035\022\001\002\000\004" +
    "\036\023\001\002\000\004\037\024\001\002\000\004\060" +
    "\025\001\002\000\004\005\026\001\002\000\004\025\027" +
    "\001\002\000\004\026\030\001\002\000\004\064\031\001" +
    "\002\000\004\061\032\001\002\000\004\023\033\001\002" +
    "\000\016\023\041\042\043\044\042\045\037\051\035\064" +
    "\034\001\002\000\010\017\uffcd\025\176\030\uffc9\001\002" +
    "\000\004\030\160\001\002\000\004\030\152\001\002\000" +
    "\004\030\uffca\001\002\000\004\024\150\001\002\000\016" +
    "\023\041\042\043\044\042\045\037\051\035\064\034\001" +
    "\002\000\004\060\140\001\002\000\004\060\044\001\002" +
    "\000\032\004\047\005\062\020\061\041\050\045\060\046" +
    "\052\047\054\050\051\060\055\064\056\065\063\067\045" +
    "\001\002\000\046\006\uffc3\007\uffc3\010\uffc3\011\uffc3\012" +
    "\uffc3\013\uffc3\014\uffc3\015\uffc3\016\uffc3\021\uffc3\022\uffc3" +
    "\025\uffc3\026\uffc3\027\uffc3\030\uffc3\031\uffc3\061\uffc3\066" +
    "\uffc3\001\002\000\046\006\uffc8\007\uffc8\010\uffc8\011\uffc8" +
    "\012\uffc8\013\uffc8\014\uffc8\015\uffc8\016\uffc8\021\uffc8\022" +
    "\uffc8\025\uffc8\026\uffc8\027\uffc8\030\uffc8\031\uffc8\061\uffc8" +
    "\066\uffc8\001\002\000\050\006\uffda\007\uffda\010\uffda\011" +
    "\uffda\012\uffda\013\uffda\014\uffda\015\uffda\016\uffda\021\uffda" +
    "\022\uffda\025\136\026\uffda\027\uffda\030\uffda\031\uffda\061" +
    "\uffda\064\uffda\066\uffda\001\002\000\050\006\uffdb\007\uffdb" +
    "\010\uffdb\011\uffdb\012\uffdb\013\uffdb\014\uffdb\015\uffdb\016" +
    "\uffdb\021\uffdb\022\uffdb\025\uffdb\026\uffdb\027\uffdb\030\uffdb" +
    "\031\uffdb\061\uffdb\064\uffdb\066\uffdb\001\002\000\006\004" +
    "\126\064\127\001\002\000\046\006\uffc2\007\uffc2\010\uffc2" +
    "\011\uffc2\012\uffc2\013\uffc2\014\uffc2\015\uffc2\016\uffc2\021" +
    "\uffc2\022\uffc2\025\uffc2\026\uffc2\027\uffc2\030\uffc2\031\uffc2" +
    "\061\uffc2\066\uffc2\001\002\000\040\006\067\007\101\010" +
    "\100\011\074\012\071\013\073\014\077\015\103\016\070" +
    "\021\102\022\065\025\075\030\066\061\121\066\072\001" +
    "\002\000\046\006\uffc1\007\uffc1\010\uffc1\011\uffc1\012\uffc1" +
    "\013\uffc1\014\uffc1\015\uffc1\016\uffc1\021\uffc1\022\uffc1\025" +
    "\uffc1\026\uffc1\027\uffc1\030\uffc1\031\uffc1\061\uffc1\066\uffc1" +
    "\001\002\000\032\004\047\005\062\020\061\041\050\045" +
    "\060\046\052\047\054\050\051\060\055\064\056\065\063" +
    "\067\045\001\002\000\050\006\uffd8\007\uffd8\010\uffd8\011" +
    "\uffd8\012\uffd8\013\uffd8\014\uffd8\015\uffd8\016\uffd8\021\uffd8" +
    "\022\uffd8\025\uffd8\026\uffd8\027\uffd8\030\uffd8\031\uffd8\061" +
    "\uffd8\064\uffd8\066\uffd8\001\002\000\046\006\uffbf\007\uffbf" +
    "\010\uffbf\011\uffbf\012\uffbf\013\uffbf\014\uffbf\015\uffbf\016" +
    "\uffbf\021\uffbf\022\uffbf\025\uffbf\026\uffbf\027\uffbf\030\uffbf" +
    "\031\uffbf\061\uffbf\066\uffbf\001\002\000\046\006\uffc0\007" +
    "\uffc0\010\uffc0\011\uffc0\012\uffc0\013\uffc0\014\uffc0\015\uffc0" +
    "\016\uffc0\021\uffc0\022\uffc0\025\uffc0\026\uffc0\027\uffc0\030" +
    "\uffc0\031\uffc0\061\uffc0\066\uffc0\001\002\000\032\004\047" +
    "\005\062\020\061\041\050\045\060\046\052\047\054\050" +
    "\051\060\055\064\056\065\063\067\045\001\002\000\050" +
    "\006\uffd9\007\uffd9\010\uffd9\011\uffd9\012\uffd9\013\uffd9\014" +
    "\uffd9\015\uffd9\016\uffd9\021\uffd9\022\uffd9\025\uffd9\026\uffd9" +
    "\027\uffd9\030\uffd9\031\uffd9\061\uffd9\064\uffd9\066\uffd9\001" +
    "\002\000\046\006\uffba\007\uffba\010\uffba\011\uffba\012\uffba" +
    "\013\uffba\014\uffba\015\uffba\016\uffba\021\uffba\022\uffba\025" +
    "\uffba\026\uffba\027\uffba\030\uffba\031\uffba\061\uffba\066\uffba" +
    "\001\002\000\046\006\067\007\101\010\100\011\074\012" +
    "\071\013\073\014\077\015\103\016\070\021\102\022\065" +
    "\025\075\026\uffbc\027\uffbc\030\066\031\uffbc\061\uffbc\066" +
    "\072\001\002\000\032\004\uffab\005\uffab\020\uffab\041\uffab" +
    "\045\uffab\046\uffab\047\uffab\050\uffab\060\uffab\064\uffab\065" +
    "\uffab\067\uffab\001\002\000\006\054\110\064\107\001\002" +
    "\000\032\004\uffb6\005\uffb6\020\uffb6\041\uffb6\045\uffb6\046" +
    "\uffb6\047\uffb6\050\uffb6\060\uffb6\064\uffb6\065\uffb6\067\uffb6" +
    "\001\002\000\032\004\uffad\005\uffad\020\uffad\041\uffad\045" +
    "\uffad\046\uffad\047\uffad\050\uffad\060\uffad\064\uffad\065\uffad" +
    "\067\uffad\001\002\000\032\004\uffb1\005\uffb1\020\uffb1\041" +
    "\uffb1\045\uffb1\046\uffb1\047\uffb1\050\uffb1\060\uffb1\064\uffb1" +
    "\065\uffb1\067\uffb1\001\002\000\032\004\uffb4\005\uffb4\020" +
    "\uffb4\041\uffb4\045\uffb4\046\uffb4\047\uffb4\050\uffb4\060\uffb4" +
    "\064\uffb4\065\uffb4\067\uffb4\001\002\000\032\004\uffb0\005" +
    "\uffb0\020\uffb0\041\uffb0\045\uffb0\046\uffb0\047\uffb0\050\uffb0" +
    "\060\uffb0\064\uffb0\065\uffb0\067\uffb0\001\002\000\032\004" +
    "\uffb2\005\uffb2\020\uffb2\041\uffb2\045\uffb2\046\uffb2\047\uffb2" +
    "\050\uffb2\060\uffb2\064\uffb2\065\uffb2\067\uffb2\001\002\000" +
    "\032\004\047\005\062\020\061\041\050\045\060\046\052" +
    "\047\054\050\051\060\055\064\056\065\063\067\045\001" +
    "\002\000\032\004\047\005\062\020\061\041\050\045\060" +
    "\046\052\047\054\050\051\060\055\064\056\065\063\067" +
    "\045\001\002\000\032\004\uffaf\005\uffaf\020\uffaf\041\uffaf" +
    "\045\uffaf\046\uffaf\047\uffaf\050\uffaf\060\uffaf\064\uffaf\065" +
    "\uffaf\067\uffaf\001\002\000\032\004\uffb3\005\uffb3\020\uffb3" +
    "\041\uffb3\045\uffb3\046\uffb3\047\uffb3\050\uffb3\060\uffb3\064" +
    "\uffb3\065\uffb3\067\uffb3\001\002\000\032\004\uffb5\005\uffb5" +
    "\020\uffb5\041\uffb5\045\uffb5\046\uffb5\047\uffb5\050\uffb5\060" +
    "\uffb5\064\uffb5\065\uffb5\067\uffb5\001\002\000\032\004\uffac" +
    "\005\uffac\020\uffac\041\uffac\045\uffac\046\uffac\047\uffac\050" +
    "\uffac\060\uffac\064\uffac\065\uffac\067\uffac\001\002\000\032" +
    "\004\uffae\005\uffae\020\uffae\041\uffae\045\uffae\046\uffae\047" +
    "\uffae\050\uffae\060\uffae\064\uffae\065\uffae\067\uffae\001\002" +
    "\000\046\006\067\007\101\010\100\011\074\012\071\013" +
    "\073\014\077\015\103\016\070\021\102\022\065\025\075" +
    "\026\uffc7\027\uffc7\030\066\031\uffc7\061\uffc7\066\072\001" +
    "\002\000\040\006\067\007\101\010\100\011\074\012\071" +
    "\013\073\014\077\015\103\016\070\021\102\022\065\025" +
    "\075\026\106\030\066\066\072\001\002\000\046\006\uffc6" +
    "\007\uffc6\010\uffc6\011\uffc6\012\uffc6\013\uffc6\014\uffc6\015" +
    "\uffc6\016\uffc6\021\uffc6\022\uffc6\025\uffc6\026\uffc6\027\uffc6" +
    "\030\uffc6\031\uffc6\061\uffc6\066\uffc6\001\002\000\004\060" +
    "\111\001\002\000\046\006\uffc5\007\uffc5\010\uffc5\011\uffc5" +
    "\012\uffc5\013\uffc5\014\uffc5\015\uffc5\016\uffc5\021\uffc5\022" +
    "\uffc5\025\uffc5\026\uffc5\027\uffc5\030\uffc5\031\uffc5\061\uffc5" +
    "\066\uffc5\001\002\000\036\004\047\005\062\020\061\031" +
    "\uffb7\041\050\045\060\046\052\047\054\050\051\060\055" +
    "\061\uffb7\064\056\065\063\067\045\001\002\000\042\006" +
    "\067\007\101\010\100\011\074\012\071\013\073\014\077" +
    "\015\103\016\070\021\102\022\065\025\075\030\066\031" +
    "\uffb9\061\uffb9\066\072\001\002\000\006\031\114\061\115" +
    "\001\002\000\032\004\047\005\062\020\061\041\050\045" +
    "\060\046\052\047\054\050\051\060\055\064\056\065\063" +
    "\067\045\001\002\000\046\006\uffc4\007\uffc4\010\uffc4\011" +
    "\uffc4\012\uffc4\013\uffc4\014\uffc4\015\uffc4\016\uffc4\021\uffc4" +
    "\022\uffc4\025\uffc4\026\uffc4\027\uffc4\030\uffc4\031\uffc4\061" +
    "\uffc4\066\uffc4\001\002\000\042\006\067\007\101\010\100" +
    "\011\074\012\071\013\073\014\077\015\103\016\070\021" +
    "\102\022\065\025\075\030\066\031\uffb8\061\uffb8\066\072" +
    "\001\002\000\040\006\067\007\101\010\100\011\074\012" +
    "\071\013\073\014\077\015\103\016\070\021\102\022\065" +
    "\025\075\030\066\061\120\066\072\001\002\000\046\006" +
    "\uffbb\007\uffbb\010\uffbb\011\uffbb\012\uffbb\013\uffbb\014\uffbb" +
    "\015\uffbb\016\uffbb\021\uffbb\022\uffbb\025\uffbb\026\uffbb\027" +
    "\uffbb\030\uffbb\031\uffbb\061\uffbb\066\uffbb\001\002\000\016" +
    "\023\041\042\043\044\042\045\037\051\035\064\034\001" +
    "\002\000\024\023\uffcf\024\uffcf\040\uffcf\042\uffcf\043\123" +
    "\044\uffcf\045\uffcf\051\uffcf\064\uffcf\001\002\000\016\023" +
    "\041\042\043\044\042\045\037\051\035\064\034\001\002" +
    "\000\024\023\uffd6\024\uffd6\040\uffd6\042\uffd6\043\uffd6\044" +
    "\uffd6\045\uffd6\051\uffd6\064\uffd6\001\002\000\024\023\uffd0" +
    "\024\uffd0\040\uffd0\042\uffd0\043\uffd0\044\uffd0\045\uffd0\051" +
    "\uffd0\064\uffd0\001\002\000\004\025\133\001\002\000\004" +
    "\060\130\001\002\000\036\004\047\005\062\020\061\031" +
    "\uffb7\041\050\045\060\046\052\047\054\050\051\060\055" +
    "\061\uffb7\064\056\065\063\067\045\001\002\000\006\031" +
    "\114\061\132\001\002\000\046\006\uffbd\007\uffbd\010\uffbd" +
    "\011\uffbd\012\uffbd\013\uffbd\014\uffbd\015\uffbd\016\uffbd\021" +
    "\uffbd\022\uffbd\025\uffbd\026\uffbd\027\uffbd\030\uffbd\031\uffbd" +
    "\061\uffbd\066\uffbd\001\002\000\032\004\047\005\062\020" +
    "\061\041\050\045\060\046\052\047\054\050\051\060\055" +
    "\064\056\065\063\067\045\001\002\000\040\006\067\007" +
    "\101\010\100\011\074\012\071\013\073\014\077\015\103" +
    "\016\070\021\102\022\065\025\075\026\135\030\066\066" +
    "\072\001\002\000\046\006\uffbe\007\uffbe\010\uffbe\011\uffbe" +
    "\012\uffbe\013\uffbe\014\uffbe\015\uffbe\016\uffbe\021\uffbe\022" +
    "\uffbe\025\uffbe\026\uffbe\027\uffbe\030\uffbe\031\uffbe\061\uffbe" +
    "\066\uffbe\001\002\000\004\026\137\001\002\000\050\006" +
    "\uffdc\007\uffdc\010\uffdc\011\uffdc\012\uffdc\013\uffdc\014\uffdc" +
    "\015\uffdc\016\uffdc\021\uffdc\022\uffdc\025\uffdc\026\uffdc\027" +
    "\uffdc\030\uffdc\031\uffdc\061\uffdc\064\uffdc\066\uffdc\001\002" +
    "\000\032\004\047\005\062\020\061\041\050\045\060\046" +
    "\052\047\054\050\051\060\055\064\056\065\063\067\045" +
    "\001\002\000\040\006\067\007\101\010\100\011\074\012" +
    "\071\013\073\014\077\015\103\016\070\021\102\022\065" +
    "\025\075\030\066\061\142\066\072\001\002\000\016\023" +
    "\041\042\043\044\042\045\037\051\035\064\034\001\002" +
    "\000\024\023\uffd5\024\uffd5\040\uffd5\042\uffd5\043\uffd5\044" +
    "\uffd5\045\uffd5\051\uffd5\064\uffd5\001\002\000\020\023\041" +
    "\024\146\042\043\044\042\045\037\051\035\064\034\001" +
    "\002\000\022\023\uffe7\024\uffe7\040\uffe7\042\uffe7\044\uffe7" +
    "\045\uffe7\051\uffe7\064\uffe7\001\002\000\024\023\uffd7\024" +
    "\uffd7\040\uffd7\042\uffd7\043\uffd7\044\uffd7\045\uffd7\051\uffd7" +
    "\064\uffd7\001\002\000\022\023\uffe6\024\uffe6\040\uffe6\042" +
    "\uffe6\044\uffe6\045\uffe6\051\uffe6\064\uffe6\001\002\000\004" +
    "\024\151\001\002\000\004\002\ufff6\001\002\000\004\064" +
    "\153\001\002\000\004\060\154\001\002\000\036\004\047" +
    "\005\062\020\061\031\uffb7\041\050\045\060\046\052\047" +
    "\054\050\051\060\055\061\uffb7\064\056\065\063\067\045" +
    "\001\002\000\006\031\114\061\156\001\002\000\004\027" +
    "\157\001\002\000\024\023\uffd1\024\uffd1\040\uffd1\042\uffd1" +
    "\043\uffd1\044\uffd1\045\uffd1\051\uffd1\064\uffd1\001\002\000" +
    "\006\052\161\055\162\001\002\000\004\030\167\001\002" +
    "\000\004\060\163\001\002\000\004\067\164\001\002\000" +
    "\004\061\165\001\002\000\004\027\166\001\002\000\024" +
    "\023\uffd3\024\uffd3\040\uffd3\042\uffd3\043\uffd3\044\uffd3\045" +
    "\uffd3\051\uffd3\064\uffd3\001\002\000\004\053\170\001\002" +
    "\000\004\060\171\001\002\000\032\004\047\005\062\020" +
    "\061\041\050\045\060\046\052\047\054\050\051\060\055" +
    "\064\056\065\063\067\045\001\002\000\040\006\067\007" +
    "\101\010\100\011\074\012\071\013\073\014\077\015\103" +
    "\016\070\021\102\022\065\025\075\030\066\061\173\066" +
    "\072\001\002\000\004\027\174\001\002\000\024\023\uffd4" +
    "\024\uffd4\040\uffd4\042\uffd4\043\uffd4\044\uffd4\045\uffd4\051" +
    "\uffd4\064\uffd4\001\002\000\004\017\201\001\002\000\032" +
    "\004\047\005\062\020\061\041\050\045\060\046\052\047" +
    "\054\050\051\060\055\064\056\065\063\067\045\001\002" +
    "\000\040\006\067\007\101\010\100\011\074\012\071\013" +
    "\073\014\077\015\103\016\070\021\102\022\065\025\075" +
    "\026\200\030\066\066\072\001\002\000\004\017\uffce\001" +
    "\002\000\032\004\047\005\062\020\061\041\050\045\060" +
    "\046\052\047\054\050\051\060\203\064\056\065\063\067" +
    "\045\001\002\000\040\006\067\007\101\010\100\011\074" +
    "\012\071\013\073\014\077\015\103\016\070\021\102\022" +
    "\065\025\075\027\uffcc\030\066\066\072\001\002\000\032" +
    "\004\047\005\062\020\061\041\050\045\060\046\052\047" +
    "\054\050\051\060\055\064\056\065\063\067\045\001\002" +
    "\000\004\027\205\001\002\000\024\023\uffd2\024\uffd2\040" +
    "\uffd2\042\uffd2\043\uffd2\044\uffd2\045\uffd2\051\uffd2\064\uffd2" +
    "\001\002\000\040\006\uffbf\007\uffbf\010\uffbf\011\uffbf\012" +
    "\uffbf\013\uffbf\014\uffbf\015\uffbf\016\uffbf\021\uffbf\022\uffbf" +
    "\025\uffbf\030\uffbf\061\207\066\uffbf\001\002\000\004\051" +
    "\210\001\002\000\004\030\211\001\002\000\004\056\212" +
    "\001\002\000\004\030\213\001\002\000\004\057\214\001" +
    "\002\000\004\060\215\001\002\000\004\061\216\001\002" +
    "\000\004\027\uffcb\001\002\000\004\023\ufff3\001\002\000" +
    "\004\023\ufff4\001\002\000\020\004\ufff1\005\ufff1\024\ufff1" +
    "\033\ufff1\034\ufff1\041\ufff1\064\ufff1\001\002\000\020\004" +
    "\047\005\062\024\226\033\232\034\224\041\050\064\056" +
    "\001\002\000\020\004\uffef\005\uffef\024\uffef\033\uffef\034" +
    "\uffef\041\uffef\064\uffef\001\002\000\014\004\047\005\062" +
    "\036\265\041\050\064\262\001\002\000\004\060\236\001" +
    "\002\000\020\004\ufff5\005\ufff5\024\ufff5\033\ufff5\034\ufff5" +
    "\041\ufff5\064\ufff5\001\002\000\004\064\234\001\002\000" +
    "\020\004\ufff0\005\ufff0\024\ufff0\033\ufff0\034\ufff0\041\ufff0" +
    "\064\ufff0\001\002\000\020\004\uffee\005\uffee\024\uffee\033" +
    "\uffee\034\uffee\041\uffee\064\uffee\001\002\000\004\064\233" +
    "\001\002\000\010\023\ufff2\062\016\063\017\001\002\000" +
    "\004\027\235\001\002\000\032\004\uffed\005\uffed\023\uffed" +
    "\024\uffed\033\uffed\034\uffed\041\uffed\042\uffed\044\uffed\045" +
    "\uffed\051\uffed\064\uffed\001\002\000\014\004\047\005\062" +
    "\041\050\061\uffdf\064\056\001\002\000\006\031\257\061" +
    "\uffe0\001\002\000\004\064\256\001\002\000\004\061\242" +
    "\001\002\000\004\023\243\001\002\000\024\004\uffe9\005" +
    "\uffe9\023\uffe9\041\uffe9\042\uffe9\044\uffe9\045\uffe9\051\uffe9" +
    "\064\uffe9\001\002\000\004\024\255\001\002\000\024\004" +
    "\047\005\062\023\041\041\050\042\043\044\042\045\037" +
    "\051\035\064\247\001\002\000\022\023\041\024\uffe1\040" +
    "\252\042\043\044\042\045\037\051\035\064\034\001\002" +
    "\000\012\017\uffcd\025\176\030\uffc9\064\uffd8\001\002\000" +
    "\024\004\uffe8\005\uffe8\023\uffe8\041\uffe8\042\uffe8\044\uffe8" +
    "\045\uffe8\051\uffe8\064\uffe8\001\002\000\004\024\uffe3\001" +
    "\002\000\032\004\047\005\062\020\061\041\050\045\060" +
    "\046\052\047\054\050\051\060\055\064\056\065\063\067" +
    "\045\001\002\000\040\006\067\007\101\010\100\011\074" +
    "\012\071\013\073\014\077\015\103\016\070\021\102\022" +
    "\065\025\075\027\254\030\066\066\072\001\002\000\004" +
    "\024\uffe2\001\002\000\020\004\uffec\005\uffec\024\uffec\033" +
    "\uffec\034\uffec\041\uffec\064\uffec\001\002\000\006\031\uffde" +
    "\061\uffde\001\002\000\012\004\047\005\062\041\050\064" +
    "\056\001\002\000\004\064\261\001\002\000\006\031\uffdd" +
    "\061\uffdd\001\002\000\006\060\uffeb\064\uffd8\001\002\000" +
    "\004\064\266\001\002\000\004\064\uffe5\001\002\000\004" +
    "\064\uffe4\001\002\000\004\060\uffea\001\002\000\006\027" +
    "\ufff8\030\ufff8\001\002\000\006\027\ufff9\030\271\001\002" +
    "\000\006\064\274\066\275\001\002\000\004\027\273\001" +
    "\002\000\006\032\ufffb\033\ufffb\001\002\000\006\027\ufff7" +
    "\030\ufff7\001\002\000\004\027\ufffa\001\002\000\004\002" +
    "\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\274\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\006\004\007\005\006\001\001\000\004\007\267" +
    "\001\001\000\002\001\001\000\006\010\012\011\010\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\012\014\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\026" +
    "\037\031\035\001\001\000\004\036\174\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\016\143\026\144\031\035\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\025\056\032\052\033" +
    "\045\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\035\075\001\001\000\002\001\001\000\010" +
    "\025\056\032\116\033\045\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\025\056\032\063" +
    "\033\045\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\035\075\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\025\056\032\104\033\045\001\001\000\010\025\056\032" +
    "\103\033\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\035\075\001\001\000\004\035\075\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\025" +
    "\056\032\111\033\045\034\112\001\001\000\004\035\075" +
    "\001\001\000\002\001\001\000\010\025\056\032\115\033" +
    "\045\001\001\000\002\001\001\000\004\035\075\001\001" +
    "\000\004\035\075\001\001\000\002\001\001\000\006\026" +
    "\121\031\035\001\001\000\004\027\123\001\001\000\006" +
    "\026\124\031\035\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\025\056" +
    "\032\111\033\045\034\130\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\025\056\032\133\033\045\001\001" +
    "\000\004\035\075\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\025\056\032\140\033\045" +
    "\001\001\000\004\035\075\001\001\000\006\026\142\031" +
    "\035\001\001\000\002\001\001\000\006\026\146\031\035" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\025\056\032\111\033\045\034" +
    "\154\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\025\056\032\171\033\045\001\001\000\004\035\075" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\025\056\032\176\033\045\001\001\000\004" +
    "\035\075\001\001\000\002\001\001\000\012\025\056\030" +
    "\203\032\201\033\045\001\001\000\004\035\075\001\001" +
    "\000\010\025\205\032\116\033\045\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\013" +
    "\221\001\001\000\014\011\230\014\227\017\222\025\226" +
    "\037\224\001\001\000\002\001\001\000\006\020\262\025" +
    "\263\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\023\240\024\236\025\237\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\015\244\021\243\001\001\000\002\001" +
    "\001\000\014\014\247\016\245\025\226\026\144\031\035" +
    "\001\001\000\010\022\250\026\146\031\035\001\001\000" +
    "\004\036\174\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\025\056\032\252\033\045\001\001\000\004\035" +
    "\075\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\025\257\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\271\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	
Scanner scanner;
public AST raiz;

	public parser(java.io.Reader input){
	scanner = new Scanner(input);
	}



	public String errores(int sys)
{
	if (sys == 3)
		return("TSTRING");
	else if (sys == 6)
		return("MULT");
	else if (sys == 5)
		return("RESTA");
	else if (sys == 45)
		return("PRINTLN");
	else if (sys == 44)
		return("OUT");
	else if (sys == 31)
		return("STATIC");
	else if (sys == 17)
		return("AND");
	else if (sys == 11)
		return("MEN_IG");
	else if (sys == 53)
		return("IMPLEM");
	else if (sys == 48)
		return("IN");
	else if (sys == 16)
		return("OR");
	else if (sys == 35)
		return("BOOL");
	else if (sys == 29)
		return("CLASS");
	else if (sys == 50)
		return("PARENTI");
	else if (sys == 7)
		return("DIV");
	else if (sys == 25)
		return("NUM");
	else if (sys == 4)
		return("SUMA");
	else if (sys == 47)
		return("EXIT");
	else if (sys == 36)
		return("IF");
	else if (sys == 33)
		return("MAIN");
	else if (sys == 51)
		return("PARENTD");
	else if (sys == 39)
		return("THIS");
	else if (sys == 27)
		return("ID");
	else if (sys == 22)
		return("PYCOMA");
	else if (sys == 43)
		return("SYSTEM");
	else if (sys == 34)
		return("RETURN");
	else if (sys == 40)
		return("TRUE");
	else if (sys == 42)
		return("NEW");
	else if (sys == 24)
		return("COMA");
	else if (sys == 8)
		return("DIF");	
	else if (sys == 20)
		return("CORCHI");
	else if (sys == 9)
		return("IG_IG");
	else if (sys == 32)
		return("VOID");
	else if (sys == 21)
		return("CORCHD");
	else if (sys == 28)
		return("IMPORT");
	else if (sys == 2)
		return("TINT");
	else if (sys == 15)
		return("NEG");
	else if (sys == 37)
		return("ELSE");
	else if (sys == 23)
		return("PUNTO");
	else if (sys == 49)
		return("READ");
	else if (sys == 10)
		return("MEN");
	else if (sys == 38)
		return("WHILE");
	else if (sys == 30)
		return("PUBLIC");
	else if (sys == 52)
		return("EXTENDS");
	else if (sys == 14)
		return("ASIGN");
	else if (sys == 26)
		return("STRING_CONS");
	else if (sys == 18)
		return("LLAVEI");
	else if (sys == 41)
		return("FALSE");
	else if (sys == 12)
		return("MAY_IG");
	else if (sys == 19)
		return("LLAVED");
	else if (sys == 13)
		return("MAY");
	else if (sys == 46)
		return("LENGTH");
	else
		return("error");
}
public void syntax_error(Symbol cur_token)
{
	if (cur_token.sym == 3)
		report_error("No se esperaba un 'String'", cur_token);
	else if (cur_token.sym == 6)
		report_error("No se esperaba un '*'", cur_token);
	else if (cur_token.sym == 5)
		report_error("No se esperaba un '-'", cur_token);
	else if (cur_token.sym == 45)
		report_error("No se esperaba un 'println'", cur_token);
	else if (cur_token.sym == 44)
		report_error("No se esperaba un 'out'", cur_token);
	else if (cur_token.sym == 31)
		report_error("No se esperaba un 'static'", cur_token);
	else if (cur_token.sym == 17)
		report_error("No se esperaba un '&&'", cur_token);
	else if (cur_token.sym == 11)
		report_error("No se esperaba un '<='", cur_token);
	else if (cur_token.sym == 53)
		report_error("No se esperaba un 'implements'", cur_token);
	else if (cur_token.sym == 48)
		report_error("No se esperaba un 'in'", cur_token);
	else if (cur_token.sym == 16)
		report_error("No se esperaba un '||'", cur_token);
	else if (cur_token.sym == 35)
		report_error("No se esperaba un 'boolean'", cur_token);
	else if (cur_token.sym == 29)
		report_error("No se esperaba un 'class'", cur_token);
	else if (cur_token.sym == 50)
		report_error("No se esperaba un '('", cur_token);
	else if (cur_token.sym == 7)
		report_error("No se esperaba un '/'", cur_token);
	else if (cur_token.sym == 25)
		report_error("No se esperaba un valor numérico", cur_token);
	else if (cur_token.sym == 4)
		report_error("No se esperaba un '+'", cur_token);
	else if (cur_token.sym == 47)
		report_error("No se esperaba un 'exit'", cur_token);
	else if (cur_token.sym == 36)
		report_error("No se esperaba un 'if'", cur_token);
	else if (cur_token.sym == 33)
		report_error("No se esperaba un 'main'", cur_token);
	else if (cur_token.sym == 51)
		report_error("No se esperaba un ')'", cur_token);
	else if (cur_token.sym == 39)
		report_error("No se esperaba un 'this'", cur_token);
	else if (cur_token.sym == 27)
		report_error("No se esperaba un identificador", cur_token);
	else if (cur_token.sym == 22)
		report_error("No se esperaba un ';'", cur_token);
	else if (cur_token.sym == 43)
		report_error("No se esperaba un 'system'", cur_token);
	else if (cur_token.sym == 34)
		report_error("No se esperaba un 'return'", cur_token);
	else if (cur_token.sym == 40)
		report_error("No se esperaba un 'true'", cur_token);
	else if (cur_token.sym == 42)
		report_error("No se esperaba un 'new'", cur_token);
	else if (cur_token.sym == 24)
		report_error("No se esperaba un ','", cur_token);
	else if (cur_token.sym == 8)
		report_error("No se esperaba un '!='", cur_token);
	else if (cur_token.sym == 20)
		report_error("No se esperaba un '['", cur_token);
	else if (cur_token.sym == 9)
		report_error("No se esperaba un '=='", cur_token);
	else if (cur_token.sym == 32)
		report_error("No se esperaba un 'void'", cur_token);
	else if (cur_token.sym == 21)
		report_error("No se esperaba un ']'", cur_token);
	else if (cur_token.sym == 28)
		report_error("No se esperaba un 'import'", cur_token);
	else if (cur_token.sym == 2)
		report_error("No se esperaba un 'int'", cur_token);
	else if (cur_token.sym == 15)
		report_error("No se esperaba un '!'", cur_token);
	else if (cur_token.sym == 37)
		report_error("No se esperaba un 'else'", cur_token);
	else if (cur_token.sym == 23)
		report_error("No se esperaba un '.'", cur_token);
	else if (cur_token.sym == 49)
		report_error("No se esperaba un 'read'", cur_token);
	else if (cur_token.sym == 10)
		report_error("No se esperaba un '<'", cur_token);
	else if (cur_token.sym == 38)
		report_error("No se esperaba un 'while'", cur_token);
	else if (cur_token.sym == 30)
		report_error("No se esperaba un 'public'", cur_token);
	else if (cur_token.sym == 52)
		report_error("No se esperaba un 'extends'", cur_token);
	else if (cur_token.sym == 14)
		report_error("No se esperaba un '='", cur_token);
	else if (cur_token.sym == 26)
		report_error("No se esperaba una cadena de texto", cur_token);
	else if (cur_token.sym == 18)
		report_error("No se esperaba un '{'", cur_token);
	else if (cur_token.sym == 41)
		report_error("No se esperaba un 'false'", cur_token);
	else if (cur_token.sym == 12)
		report_error("No se esperaba un '>='", cur_token);
	else if (cur_token.sym == 19)
		report_error("No se esperaba un '}'", cur_token);
	else if (cur_token.sym == 13)
		report_error("No se esperaba un '>'", cur_token);
	else if (cur_token.sym == 46)
		report_error("No se esperaba un 'length'", cur_token);	
	else 
		report_error("error", cur_token);}
 public void report_error(String message, Object info) {
   StringBuffer m = new StringBuffer("Error ");

   if (info instanceof java_cup.runtime.Symbol) {
     m.append( "(" + errores(((java_cup.runtime.Symbol)info).sym) +")" );
     m.append(" en fila "+ ((java_cup.runtime.Symbol)info).left + " columna " + ((java_cup.runtime.Symbol)info).right );
     
     if (((java_cup.runtime.Symbol)info).value != null)
       m.append(". Lexema: " + ((java_cup.runtime.Symbol)info).value.toString());
     
   }
   m.append(" : "+message);
   
   System.out.println(m);
 }

	public void report_fatal_error(String message, Object info) {
		report_error(message, info);
		throw new RuntimeException("Error Fatal de Sintáxis");
  }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // op ::= AND 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // op ::= OR 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // op ::= MAY 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // op ::= MAY_IG 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // op ::= MEN_IG 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // op ::= MEN 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // op ::= IG_IG 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // op ::= DIF 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // op ::= DIV 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // op ::= MULT 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // op ::= RESTA 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // op ::= SUMA 
            {
              OpAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("op",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // explist ::= 
            {
              ExpListAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("explist",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // explist ::= explist COMA exp 
            {
              ExpListAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ExpListAST a = (ExpListAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpAST b = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoVariasExpListAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("explist",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // explist ::= exp 
            {
              ExpListAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoUnExpListAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("explist",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expsimpl ::= STRING_CONS 
            {
              ExpSimplAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoExpSimplString_ConsAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expsimpl ::= PARENTI exp PARENTD 
            {
              ExpSimplAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoExpSimplExp3AST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expsimpl ::= NEG exp 
            {
              ExpSimplAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoExpSimplExp2AST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expsimpl ::= NEW ID PARENTI explist PARENTD 
            {
              ExpSimplAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ExpListAST b = (ExpListAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoExpSimplIdAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expsimpl ::= NEW TINT CORCHI exp CORCHD 
            {
              ExpSimplAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoExpSimplExp1AST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expsimpl ::= type 
            {
              ExpSimplAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TypeAST a = (TypeAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoExpSimplTypeAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expsimpl ::= THIS 
            {
              ExpSimplAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expsimpl ::= FALSE 
            {
              ExpSimplAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expsimpl ::= TRUE 
            {
              ExpSimplAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expsimpl ::= NUM 
            {
              ExpSimplAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoExpSimplNumAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expsimpl",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // exp ::= exp PUNTO ID PARENTI explist PARENTD 
            {
              ExpAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ExpListAST c = (ExpListAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoExpExp4AST(a,b,c);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // exp ::= exp PUNTO LENGTH 
            {
              ExpAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		RESULT = new CuerpoExpExp3AST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // exp ::= exp CORCHI exp CORCHD 
            {
              ExpAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ExpAST b = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoExpExp2AST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // exp ::= exp op exp 
            {
              ExpAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpAST b = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoExpExp1AST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // exp ::= expsimpl 
            {
              ExpAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpSimplAST a = (ExpSimplAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoExpExpSimplAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // thisaux ::= ID 
            {
              ThisAuxAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoThisAuxIdAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("thisaux",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // thisaux ::= THIS 
            {
              ThisAuxAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("thisaux",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // systemaux ::= PARENTI type PARENTD SYSTEM PUNTO IN PUNTO READ PARENTI PARENTD 
            {
              SystemAuxAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		TypeAST a = (TypeAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		RESULT = new CuerpoSystemAuxTypeAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("systemaux",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // systemaux ::= exp 
            {
              SystemAuxAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoSystemAuxExpAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("systemaux",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // idaux ::= 
            {
              IdAuxAST RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("idaux",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // idaux ::= CORCHI exp CORCHD 
            {
              IdAuxAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoIdAuxExpAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("idaux",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // ifaux ::= 
            {
              IfAuxAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ifaux",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // ifaux ::= ELSE statement 
            {
              IfAuxAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		StatementAST a = (StatementAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoIfAuxAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ifaux",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // statement ::= thisaux PUNTO ID PARENTI explist PARENTD PYCOMA 
            {
              StatementAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		ThisAuxAST a = (ThisAuxAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ExpListAST c = (ExpListAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		RESULT = new CuerpoStatementThisAST(a,b,c);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // statement ::= ID idaux ASIGN systemaux PYCOMA 
            {
              StatementAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		IdAuxAST b = (IdAuxAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		SystemAuxAST c = (SystemAuxAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoStatementIdAST(a,b,c);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // statement ::= SYSTEM PUNTO EXIT PARENTI NUM PARENTD PYCOMA 
            {
              StatementAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		RESULT = new CuerpoStatementSystemExitAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // statement ::= SYSTEM PUNTO OUT PUNTO PRINTLN PARENTI exp PARENTD PYCOMA 
            {
              StatementAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		RESULT = new CuerpoStatementSystemOutAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // statement ::= WHILE PARENTI exp PARENTD statement 
            {
              StatementAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		StatementAST b = (StatementAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoStatementWhileAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // statement ::= IF PARENTI exp PARENTD statement ifaux 
            {
              StatementAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		StatementAST b = (StatementAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		IfAuxAST c = (IfAuxAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoStatementIfAST(a,b,c);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // statement ::= LLAVEI variasstatement LLAVED 
            {
              StatementAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		VariasStatementAST a = (VariasStatementAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoStatementVariasAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("statement",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // type ::= ID 
            {
              TypeAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoTypeAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // type ::= TSTRING 
            {
              TypeAST RESULT =null;
		RESULT= null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // type ::= TINT 
            {
              TypeAST RESULT =null;
		RESULT= null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // type ::= BOOL 
            {
              TypeAST RESULT =null;
		RESULT= null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // type ::= TINT CORCHI CORCHD 
            {
              TypeAST RESULT =null;
		RESULT= null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // formallistaux ::= formallistaux COMA type ID 
            {
              FormalListAuxAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		FormalListAuxAST a = (FormalListAuxAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TypeAST b = (TypeAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoFormalListAuxVariosAST(a,b,c);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formallistaux",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // formallistaux ::= type ID 
            {
              FormalListAuxAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TypeAST a = (TypeAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoFormalListAuxUnoAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formallistaux",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // formallist ::= 
            {
              FormalListAST RESULT =null;
		RESULT= null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formallist",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // formallist ::= formallistaux 
            {
              FormalListAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		FormalListAuxAST a = (FormalListAuxAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoFormalListAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("formallist",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // methoddeclauxdos ::= 
            {
              MethodDeclAuxDosAST RESULT =null;
		RESULT= null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclauxdos",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // methoddeclauxdos ::= RETURN exp PYCOMA 
            {
              MethodDeclAuxDosAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ExpAST a = (ExpAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoMethodDeclAuxDosAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclauxdos",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // methoddeclauxuno ::= variasvardecl variasstatement methoddeclauxdos 
            {
              MethodDeclAuxUnoAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		VariasVarDeclAST a = (VariasVarDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		VariasStatementAST b = (VariasStatementAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MethodDeclAuxDosAST c = (MethodDeclAuxDosAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoMethodDeclAuxUnoAST(a,b,c);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclauxuno",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // methoddeclaux ::= VOID 
            {
              MethodDeclAuxAST RESULT =null;
		RESULT= null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclaux",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // methoddeclaux ::= type 
            {
              MethodDeclAuxAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TypeAST a = (TypeAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoMethodDeclAuxAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddeclaux",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // variasstatement ::= variasstatement statement 
            {
              VariasStatementAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		VariasStatementAST a = (VariasStatementAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		StatementAST b = (StatementAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoVariasStatementVariasAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasstatement",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // variasstatement ::= statement 
            {
              VariasStatementAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		StatementAST a = (StatementAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT= new CuerpoVariasStatementunoAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasstatement",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // variasvardecl ::= variasvardecl vardecl 
            {
              VariasVarDeclAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		VariasVarDeclAST a = (VariasVarDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		VarDeclAST b = (VarDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT= new CuerpoVariasVarDeclAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasvardecl",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // variasvardecl ::= 
            {
              VariasVarDeclAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasvardecl",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // constrdeclormethoddecl ::= PUBLIC methoddeclaux ID 
            {
              ConstrDeclorMethodDeclAST RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		MethodDeclAuxAST b = (MethodDeclAuxAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoConstrDeclorMethodDeclMethodDeclAST(b,c);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("constrdeclormethoddecl",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // constrdeclormethoddecl ::= PUBLIC ID 
            {
              ConstrDeclorMethodDeclAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoConstrDeclorMethodDeclConstrDeclAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("constrdeclormethoddecl",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // methoddecl ::= constrdeclormethoddecl PARENTI formallist PARENTD LLAVEI methoddeclauxuno LLAVED 
            {
              MethodDeclAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		ConstrDeclorMethodDeclAST a = (ConstrDeclorMethodDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		FormalListAST b = (FormalListAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		MethodDeclAuxUnoAST c = (MethodDeclAuxUnoAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoMethodDeclAST(a,b,c);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("methoddecl",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // vardecl ::= type ID PYCOMA 
            {
              VarDeclAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		TypeAST a = (TypeAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoVarDeclAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vardecl",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // bodydecl ::= bodydecl classdecl 
            {
              BodyDeclAST RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		BodyDeclAST e = (BodyDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ClassDeclAST f = (ClassDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoBodyDeclClassDeclAST(e,f);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bodydecl",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // bodydecl ::= bodydecl methoddecl 
            {
              BodyDeclAST RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		BodyDeclAST c = (BodyDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MethodDeclAST d = (MethodDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoBodyDeclMethodDeclAST(c,d);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bodydecl",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // bodydecl ::= bodydecl vardecl 
            {
              BodyDeclAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		BodyDeclAST a = (BodyDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		VarDeclAST b = (VarDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoBodyDeclVarDeclAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bodydecl",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // bodydecl ::= 
            {
              BodyDeclAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bodydecl",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // classdeclaux ::= 
            {
              ClassDeclAuxAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("classdeclaux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // classdeclaux ::= IMPLEM ID 
            {
              ClassDeclAuxAST RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoImplementsClassDeclAuxAST(b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("classdeclaux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // classdeclaux ::= EXTENDS ID 
            {
              ClassDeclAuxAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoExtendsClassDeclAuxAST(a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("classdeclaux",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // classdecl ::= CLASS ID classdeclaux LLAVEI bodydecl LLAVED 
            {
              ClassDeclAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ClassDeclAuxAST b = (ClassDeclAuxAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		BodyDeclAST c = (BodyDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = new CuerpoClassDeclAST(a,b,c);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("classdecl",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // mainclass ::= CLASS ID LLAVEI PUBLIC STATIC VOID MAIN PARENTI TSTRING CORCHI CORCHD ID PARENTD LLAVEI statement LLAVED LLAVED 
            {
              MainClassAST RESULT =null;
		int id1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-15)).left;
		int id1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-15)).right;
		String id1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-15)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String id2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		StatementAST a = (StatementAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		RESULT= new CuerpoMainClassAST(id1, id2,a);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("mainclass",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-16)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // typename ::= typename PUNTO ID 
            {
              TypeNameAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		TypeNameAST a = (TypeNameAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoVariasTypeNameAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("typename",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // typename ::= ID 
            {
              TypeNameAST RESULT =null;
		int ideleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ideright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String ide = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT= new CuerpoUnTypeNameAST(ide);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("typename",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // importdeclaux ::= 
            {
              ImportDeclAuxAST RESULT =null;
		RESULT=null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("importdeclaux",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // importdeclaux ::= PUNTO MULT 
            {
              ImportDeclAuxAST RESULT =null;
		int ideleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int ideright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String ide = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoImportDeclAuxAST(ide);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("importdeclaux",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // importdecl ::= IMPORT typename importdeclaux PYCOMA 
            {
              ImportDeclAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		TypeNameAST a = (TypeNameAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ImportDeclAuxAST b = (ImportDeclAuxAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT= new CuerpoImportDeclAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("importdecl",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // variasclassdecl ::= variasclassdecl classdecl 
            {
              VariasClassDeclAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		VariasClassDeclAST a = (VariasClassDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ClassDeclAST b = (ClassDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoVariasClassDeclAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasclassdecl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // variasclassdecl ::= 
            {
              VariasClassDeclAST RESULT =null;
		RESULT=null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasclassdecl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // variasimportdecl ::= variasimportdecl importdecl 
            {
              VariasImportDeclAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		VariasImportDeclAST a = (VariasImportDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ImportDeclAST b = (ImportDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = new CuerpoVariasImportDeclAST(a,b);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasimportdecl",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // variasimportdecl ::= 
            {
              VariasImportDeclAST RESULT =null;
		RESULT = null;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variasimportdecl",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // program ::= variasimportdecl variasclassdecl mainclass 
            {
              ProgramAST RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		VariasImportDeclAST a = (VariasImportDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		VariasClassDeclAST b = (VariasClassDeclAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MainClassAST c = (MainClassAST)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
				parser.raiz = new CuerpoProgramAST(a,b,c);
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ProgramAST start_val = (ProgramAST)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

