
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 16 21:11:20 CST 2013
//----------------------------------------------------

package compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TSTRING = 3;
  public static final int MULT = 52;
  public static final int RESTA = 5;
  public static final int STRING_CONS = 51;
  public static final int PRINTLN = 41;
  public static final int OUT = 40;
  public static final int STATIC = 27;
  public static final int AND = 16;
  public static final int MEN_IG = 10;
  public static final int IMPLEM = 49;
  public static final int IN = 44;
  public static final int OR = 15;
  public static final int BOOL = 31;
  public static final int CLASS = 25;
  public static final int PARENTI = 46;
  public static final int DIV = 6;
  public static final int NUM = 53;
  public static final int SUMA = 4;
  public static final int EXIT = 43;
  public static final int MAIN = 29;
  public static final int IF = 32;
  public static final int PARENTD = 47;
  public static final int THIS = 35;
  public static final int ID = 50;
  public static final int PYCOMA = 21;
  public static final int EOF = 0;
  public static final int SYSTEM = 39;
  public static final int RETURN = 30;
  public static final int TRUE = 36;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int COMA = 23;
  public static final int DIF = 7;
  public static final int CORCHI = 19;
  public static final int IG_IG = 8;
  public static final int VOID = 28;
  public static final int CORCHD = 20;
  public static final int IMPORT = 24;
  public static final int TINT = 2;
  public static final int NEG = 14;
  public static final int ELSE = 33;
  public static final int PUNTO = 22;
  public static final int READ = 45;
  public static final int MEN = 9;
  public static final int WHILE = 34;
  public static final int PUBLIC = 26;
  public static final int EXTENDS = 48;
  public static final int ASIGN = 13;
  public static final int LLAVEI = 17;
  public static final int FALSE = 37;
  public static final int MAY_IG = 11;
  public static final int LLAVED = 18;
  public static final int MAY = 12;
  public static final int LENGTH = 42;
}

